### ISSUE TITLE
Vue Paypal Checkout Support SSR ?

### ISSUE THREAD

**Issue by suryaadtmaja** [khoanguyen96/vue-paypal-checkout#53]
i'm going to use vue paypal checkout for my project in nuxt, but before I use it, i'm going ask, is it vue paypal checkout  is support SSR ?

thank you

**Comment by IlyaSemenov** [comment]
No, don't bother with this one. It will crash immediately on import with:

```
{ ReferenceError: window is not defined
    at Object../node_modules/post-robot/src/conf/index.js (node_modules/paypal-checkout/dist/checkout.lib.js:2436:0)
    at __webpack_require__ (node_modules/paypal-checkout/dist/checkout.lib.js:13:0)
    at Object../node_modules/post-robot/src/lib/index.js (node_modules/paypal-checkout/dist/checkout.lib.js:3187:0)
    at __webpack_require__ (node_modules/paypal-checkout/dist/checkout.lib.js:13:0)
    at Object../node_modules/post-robot/src/index.js (node_modules/paypal-checkout/dist/checkout.lib.js:2524:0)
    at __webpack_require__ (node_modules/paypal-checkout/dist/checkout.lib.js:13:0)
    at Object../node_modules/xcomponent/src/index.js (node_modules/paypal-checkout/dist/checkout.lib.js:6828:0)
    at __webpack_require__ (node_modules/paypal-checkout/dist/checkout.lib.js:13:0)
    at Object../src/index.js (node_modules/paypal-checkout/dist/checkout.lib.js:10355:0)
    at __webpack_require__ (node_modules/paypal-checkout/dist/checkout.lib.js:13:0)
    at modules../node_modules/Base64/base64.js.object (node_modules/paypal-checkout/dist/checkout.lib.js:39:0)
    at pages/tokens.js:781:6
    at exports.modules.528.installedModules (node_modules/paypal-checkout/dist/checkout.lib.js:2:0)
    at Object.528 (node_modules/paypal-checkout/dist/checkout.lib.js:3:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2686f665539dc9063c07:25:0)
    at Object.527 (node_modules/paypal-checkout/index.js:5:0) statusCode: 500, name: 'ReferenceError' }
```

**Comment by suryaadtmaja** [comment]
No, i do use this package, and it's actually work.
just add 
    { src: '~/plugins/paypal.js', ssr: false }
  ],
  ** Build configuration
  */
  build: {
    vendor: [
      'vue-paypal-checkout'
    ],

and in plugins :

import Vue from 'vue'
import PayPal from 'vue-paypal-checkout'
Vue.component('paypal-checkout', PayPal)

**Comment by khoanguyen96** [comment]
Thanks for the PR to use the component with Nuxt.js!

**Comment by suryaadtmaja** [comment]
@andriyfm did you install vue-paypal-checkout on your project? the error looks like you're not installing it

**Comment by andriyfm** [comment]
I cancel to use this package, maybe later.

**Comment by mogalmahesh** [comment]
Like @filsuck said, i added payal.js file and added paypal component and  made changes in nuxt config js as well. But i am still getting  " window is not defined" error.
Here are changes i have made

paypal.js
```
import Vue from 'vue'
import PayPal from 'vue-paypal-checkout'
Vue.component('paypal-checkout', PayPal')
```

nuxt-config.js
```
plugins: [
  { src: '~/plugins/paypal.js', ssr: false }
  ],

build: {
vendor: [
      'vue-paypal-checkout'
    ]
}
```

**Comment by filsuck** [comment]
> Thanks @filsuck. It worked

You're welcome
